using Microsoft.EntityFrameworkCore.Migrations;

namespace Martians.API.Migrations
{
    public partial class AutoGeneratedKeysMigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
